---
- name: reload systemd for php_fpm_exporters
  become: true
  systemd:
    daemon_reload: true

- name: restart php_fpm_exporters
  become: true
  systemd:
    name: php_fpm_exporter-{{ item.name }}.service
    state: restarted
  with_items: "{{ php_fpm_pools }}"

- name: restart node_exporter
  service: name=node_exporter state=restarted  

- name: daemon-reload-node_exporter
  systemd:
    name: node_exporter
    daemon_reload: yes
    state: restarted  